name: Update Package Managers

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., 0.1.1)'
        required: false
        type: string

permissions:
  contents: read

jobs:
  notify-package-repo:
    name: Notify Package Repository
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Notifying package repository of version: $VERSION"

      - name: Trigger package repository update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/CaddyGlow/homebrew-packages/dispatches \
            -d '{
              "event_type": "update-package",
              "client_payload": {
                "tool": "quickctx",
                "version": "${{ steps.version.outputs.VERSION }}",
                "repository": "${{ github.repository }}"
              }
            }'

      - name: Summary
        run: |
          echo "Triggered update in homebrew-packages repository"
          echo "  Tool: quickctx"
          echo "  Version: ${{ steps.version.outputs.VERSION }}"
          echo ""
          echo "Check workflow status at:"
          echo "https://github.com/CaddyGlow/homebrew-packages/actions"
